GET http://localhost:8080/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJob25nb2NhbiIsImlhdCI6MTc0NTM5OTE0MiwiZXhwIjoxNzQ1Mzk5MTYyfQ.JpV3XNwBAx_yuHqbiM9CYgSvoXwOvT15RdSLz9w0u3A

### Register
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "hongocan",
  "password": "123456"
}

### Login User
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "valueLogin": "hongocan",
    "password": "123456"
}


### Refresh Token
POST http://localhost:8080/api/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJob25nb2NhbiIsImdyb3VwIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJSb2xlcyI6W119LCJpYXQiOjE3NDUzOTkwNzAsImV4cCI6MTc0NjAwMzg3MH0.eFz2CjKs6H6iGQSClCFQPEgEOeDlZ7zUQbF0Aqq8s6g"
}

### Logout
DELETE  http://localhost:8080/api/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJob25nb2NhbiIsImdyb3VwIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJSb2xlcyI6W119LCJpYXQiOjE3NDUzOTkwNzAsImV4cCI6MTc0NjAwMzg3MH0.eFz2CjKs6H6iGQSClCFQPEgEOeDlZ7zUQbF0Aqq8s6g"
}

### Get All Product
GET  http://localhost:8080/api/product/all
Content-Type: application/json

### Get Product líst
GET  http://localhost:8080/api/product/list?page=1
Content-Type: application/json

### Get Product detail
GET  http://localhost:8080/api/product/detail/1
Content-Type: application/json

### Get Group líst
GET  http://localhost:8080/api/group/list
Content-Type: application/json

### Get User líst
GET  http://localhost:8080/api/user/list?page=1
Content-Type: application/json

### Get Acccount
GET  http://localhost:8080/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJob25nb2NhbiIsImdyb3VwIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJSb2xlcyI6W119LCJpYXQiOjE3NDU0MTcyODAsImV4cCI6MTc0NTQxNzMwMH0.IiCWdgZwmYe_run1x5dgeg_wb-gN-Pgosob0ebCdzBQ

### Get List Role
GET  http://localhost:8080/api/role/list
Content-Type: application/json

### Get List Category
GET  http://localhost:8080/api/category/list
Content-Type: application/json